spring:
  application:
    name: wxchat-cloud-server-discovery
  redis:
    host: 192.168.1.113
    port: 7379
logging:
  file: logs/${spring.application.name}.log
  level:
    root: error
    com.mjoys: info
server:
  port: 8999