spring:
  application:
    name: wxchat-cloud-server
  datasource:
    url: jdbc:mysql://192.168.1.111:3306?useOldAliasMetadataBehavior=true&useSSL=false
    username: robot
    password: robot@8UHB
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: 192.168.1.113
    port: 7379
    jedis:
      pool:
        max-wait: 1
        min-idle: 1
        max-active: 10
logging:
  file: logs/${spring.application.name}.log
  level:
    root: error
    com.mjoys: info